// Demo conversation data for MVP
// Structured to match GoHighLevel API response format

export interface ConversationMessage {
  id: string
  role: "user" | "assistant" | "system"
  content: string
  timestamp: string
  type?: "sms" | "email" | "call" | "note"
  direction?: "inbound" | "outbound"
  contact_name?: string
  contact_phone?: string
  contact_email?: string
}

export interface DealConversation {
  deal_id: string
  deal_title: string
  contact_name: string
  contact_phone?: string
  contact_email?: string
  messages: ConversationMessage[]
  last_activity: string
}

export const demoConversations: Record<string, DealConversation> = {
  "deal-001": {
    deal_id: "deal-001",
    deal_title: "Acme Corp - Enterprise Package",
    contact_name: "Sarah Johnson",
    contact_phone: "+1 (555) 234-5678",
    contact_email: "sarah.johnson@acmecorp.com",
    last_activity: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-001",
        role: "user",
        content: "Hi! I'm interested in learning more about your Enterprise Package. Can you send me some information?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Sarah Johnson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-002",
        role: "assistant",
        content: "Absolutely! The Enterprise Package includes advanced analytics, priority support, and custom integrations. I can send you a detailed proposal. What's the best way to reach you?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-003",
        role: "user",
        content: "Email works great. I'm particularly interested in the analytics features.",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Sarah Johnson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-004",
        role: "assistant",
        content: "Perfect! I'll send over the proposal with details on our analytics suite. It includes real-time dashboards, custom reports, and predictive insights. Should I include pricing information?",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-005",
        role: "user",
        content: "Yes, please include pricing. I'll review it and get back to you.",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Sarah Johnson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-006",
        role: "assistant",
        content: "Great! I've sent the proposal to your email. Let me know if you have any questions. I'm here to help!",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "sarah.johnson@acmecorp.com",
      },
      {
        id: "msg-007",
        role: "system",
        content: "Email sent: Enterprise Package Proposal - Acme Corp",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 16 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-008",
        role: "assistant",
        content: "Hi Sarah, just following up on the proposal I sent. Have you had a chance to review it? I'm happy to answer any questions or schedule a call to discuss.",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "sarah.johnson@acmecorp.com",
      },
      {
        id: "msg-009",
        role: "user",
        content: "Thanks for following up. I'm still reviewing with my team. We should have feedback by next week.",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Sarah Johnson",
        contact_email: "sarah.johnson@acmecorp.com",
      },
      {
        id: "msg-010",
        role: "assistant",
        content: "Perfect! I'll circle back next week. In the meantime, if any questions come up, feel free to reach out. I'm here to help!",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "sarah.johnson@acmecorp.com",
      },
      {
        id: "msg-011",
        role: "system",
        content: "Call attempted - No answer. Left voicemail.",
        timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-012",
        role: "assistant",
        content: "Hi Sarah, checking in as promised. Did your team have a chance to review the proposal? I'm available for a call this week if you'd like to discuss.",
        timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-013",
        role: "system",
        content: "Email sent: Updated proposal with additional analytics features",
        timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
    ],
  },
  "deal-002": {
    deal_id: "deal-002",
    deal_title: "TechStart Inc - Starter Package",
    contact_name: "Mike Chen",
    contact_phone: "+1 (555) 345-6789",
    contact_email: "mike.chen@techstart.io",
    last_activity: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-009",
        role: "user",
        content: "Hey, I saw your Starter Package and it looks interesting. What's included?",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Mike Chen",
        contact_phone: "+1 (555) 345-6789",
      },
      {
        id: "msg-010",
        role: "assistant",
        content: "Hi Mike! The Starter Package is perfect for growing teams. It includes up to 10 users, basic analytics, email support, and all core features. It's $99/month. Would you like to see a demo?",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-011",
        role: "user",
        content: "That sounds good. Can we schedule something for next week?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Mike Chen",
        contact_phone: "+1 (555) 345-6789",
      },
      {
        id: "msg-012",
        role: "assistant",
        content: "Absolutely! I have availability Tuesday and Wednesday next week. What time works best for you?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-013",
        role: "user",
        content: "Tuesday afternoon would work. Let me check my calendar and confirm.",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Mike Chen",
        contact_phone: "+1 (555) 345-6789",
      },
      {
        id: "msg-014",
        role: "assistant",
        content: "Great! I'll send you a calendar invite for Tuesday at 2 PM. Looking forward to showing you the platform!",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-015",
        role: "system",
        content: "Call completed - Duration: 12 minutes. Discussed pricing and implementation timeline. Follow-up scheduled for next week.",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 345-6789",
      },
      {
        id: "msg-016",
        role: "user",
        content: "Thanks for the call! I'll review everything and get back to you.",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Mike Chen",
        contact_email: "mike.chen@techstart.io",
      },
      {
        id: "msg-017",
        role: "assistant",
        content: "Perfect! I've sent you the pricing sheet and implementation guide. Let me know if you have any questions. Talk soon!",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 1 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "mike.chen@techstart.io",
      },
      {
        id: "msg-018",
        role: "assistant",
        content: "Hey Mike, just checking in. How's the review going? Happy to answer any questions!",
        timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
    ],
  },
  "deal-003": {
    deal_id: "deal-003",
    deal_title: "Global Solutions - Premium",
    contact_name: "Jennifer Martinez",
    contact_phone: "+1 (555) 456-7890",
    contact_email: "j.martinez@globalsolutions.com",
    last_activity: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-015",
        role: "user",
        content: "Hi, we're looking for a solution that can scale with our international operations. Does your Premium package support multiple regions?",
        timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jennifer Martinez",
        contact_email: "j.martinez@globalsolutions.com",
      },
      {
        id: "msg-016",
        role: "assistant",
        content: "Yes! Our Premium package includes multi-region support, localized features, and 24/7 global support. We work with companies in 40+ countries. Would you like to discuss your specific requirements?",
        timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "j.martinez@globalsolutions.com",
      },
      {
        id: "msg-017",
        role: "user",
        content: "That's exactly what we need. Can you send me a custom quote?",
        timestamp: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jennifer Martinez",
        contact_email: "j.martinez@globalsolutions.com",
      },
      {
        id: "msg-018",
        role: "assistant",
        content: "I'd be happy to! To provide the most accurate quote, could you share: 1) Number of users, 2) Primary regions, and 3) Any specific compliance requirements?",
        timestamp: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "j.martinez@globalsolutions.com",
      },
      {
        id: "msg-019",
        role: "user",
        content: "We have about 200 users across North America, Europe, and Asia. We need GDPR compliance for Europe.",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jennifer Martinez",
        contact_email: "j.martinez@globalsolutions.com",
      },
      {
        id: "msg-020",
        role: "assistant",
        content: "Perfect! We're GDPR compliant and have data centers in all those regions. I'll prepare a custom quote based on 200 users. Should I include multi-region deployment details?",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "j.martinez@globalsolutions.com",
      },
      {
        id: "msg-021",
        role: "system",
        content: "Call scheduled for tomorrow at 2 PM EST to discuss requirements",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-022",
        role: "system",
        content: "Call completed - Duration: 25 minutes. Discussed multi-region deployment, GDPR compliance, and pricing structure. Quote sent via email.",
        timestamp: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 456-7890",
      },
      {
        id: "msg-023",
        role: "user",
        content: "Thanks for the call and the detailed quote. I'll review with our procurement team.",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jennifer Martinez",
        contact_email: "j.martinez@globalsolutions.com",
      },
      {
        id: "msg-024",
        role: "assistant",
        content: "You're welcome! Let me know if procurement has any questions. I'm here to help make this work for Global Solutions.",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "j.martinez@globalsolutions.com",
      },
    ],
  },
  "deal-004": {
    deal_id: "deal-004",
    deal_title: "InnovateCo - Growth Package",
    contact_name: "David Park",
    contact_phone: "+1 (555) 567-8901",
    contact_email: "david@innovateco.com",
    last_activity: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-020",
        role: "user",
        content: "We're a fast-growing startup. What does the Growth Package offer?",
        timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "David Park",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-021",
        role: "assistant",
        content: "The Growth Package is designed for scaling companies! It includes unlimited users, advanced features, priority support, and flexible pricing that grows with you. Plus, we offer special startup discounts. Interested?",
        timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000 + 4 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-022",
        role: "user",
        content: "The startup discount sounds interesting. What's the pricing?",
        timestamp: new Date(Date.now() - 34 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "David Park",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-023",
        role: "assistant",
        content: "For qualifying startups, we offer 20% off the first year. The Growth Package is normally $299/month, so that would be $239/month. We also have flexible payment terms. Want to see if you qualify?",
        timestamp: new Date(Date.now() - 34 * 24 * 60 * 60 * 1000 + 6 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-024",
        role: "user",
        content: "How do I qualify for the startup discount?",
        timestamp: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "David Park",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-025",
        role: "assistant",
        content: "Great question! To qualify, you need to be under 5 years old, have less than 50 employees, and be VC-backed or bootstrapped. I can send you a quick form to fill out.",
        timestamp: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-026",
        role: "system",
        content: "Call completed - Duration: 18 minutes. Discussed startup qualification criteria and pricing options. Sent qualification form via email.",
        timestamp: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-027",
        role: "user",
        content: "I filled out the form. How long does approval take?",
        timestamp: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "David Park",
        contact_email: "david@innovateco.com",
      },
      {
        id: "msg-028",
        role: "assistant",
        content: "Usually 1-2 business days. I'll let you know as soon as I hear back. In the meantime, I can set up a demo account for you to explore.",
        timestamp: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "david@innovateco.com",
      },
      {
        id: "msg-029",
        role: "assistant",
        content: "Hey David, just checking in. Did you get a chance to explore the demo account?",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
    ],
  },
  "deal-005": {
    deal_id: "deal-005",
    deal_title: "ScaleUp Ventures - Enterprise",
    contact_name: "Lisa Thompson",
    contact_phone: "+1 (555) 678-9012",
    contact_email: "lisa.thompson@scaleupventures.com",
    last_activity: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-025",
        role: "user",
        content: "We're evaluating enterprise solutions. What makes yours different?",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Lisa Thompson",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
      {
        id: "msg-026",
        role: "assistant",
        content: "Our Enterprise solution offers custom integrations, dedicated account management, SLA guarantees, and white-glove onboarding. We've helped companies like yours scale from 50 to 5000+ users. Would you like to see a case study?",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
      {
        id: "msg-027",
        role: "user",
        content: "Yes, that would be helpful. Also, what's the implementation timeline?",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Lisa Thompson",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
      {
        id: "msg-028",
        role: "assistant",
        content: "I'll send over the case study. For implementation, we typically see companies up and running in 2-4 weeks, depending on complexity. We provide a dedicated implementation specialist. Want to schedule a call to discuss your timeline?",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
      {
        id: "msg-029",
        role: "user",
        content: "Yes, let's schedule a call. I'm available next Tuesday or Wednesday afternoon.",
        timestamp: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Lisa Thompson",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
      {
        id: "msg-030",
        role: "assistant",
        content: "Perfect! I'll send you a calendar invite for Tuesday at 2 PM EST. Looking forward to discussing your implementation needs!",
        timestamp: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000 + 1 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
      {
        id: "msg-031",
        role: "system",
        content: "Call completed - Duration: 30 minutes. Discussed implementation timeline, custom requirements, and next steps. Proposal sent.",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 678-9012",
      },
      {
        id: "msg-032",
        role: "user",
        content: "Thanks for the call! The implementation timeline works for us. I'll review the proposal with my team.",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Lisa Thompson",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
      {
        id: "msg-033",
        role: "assistant",
        content: "Great to hear! Let me know if you have any questions. I'm here to help make this work for ScaleUp Ventures.",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
    ],
  },
  "deal-006": {
    deal_id: "deal-006",
    deal_title: "DataFlow Systems - Pro Package",
    contact_name: "Tom Wilson",
    contact_phone: "+1 (555) 789-0123",
    contact_email: "tom.wilson@dataflow.io",
    last_activity: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-029",
        role: "user",
        content: "Hi, I'm interested in the Pro Package. What's included?",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Tom Wilson",
        contact_phone: "+1 (555) 789-0123",
      },
      {
        id: "msg-030",
        role: "assistant",
        content: "Hi Tom! The Pro Package includes up to 50 users, advanced analytics, API access, priority support, and custom integrations. It's $199/month. Perfect for mid-size teams. Want to see a demo?",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-031",
        role: "user",
        content: "The API access is important for us. Can you tell me more about that?",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Tom Wilson",
        contact_phone: "+1 (555) 789-0123",
      },
      {
        id: "msg-032",
        role: "assistant",
        content: "Absolutely! Our API is RESTful, well-documented, and includes webhooks. You can integrate with your existing tools, build custom workflows, and automate processes. We also provide API support and examples. Want to see the docs?",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-033",
        role: "system",
        content: "Email sent: API Documentation and Integration Guide",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-034",
        role: "user",
        content: "Thanks for the docs! They look comprehensive. We're planning to integrate next month. Can we get a sandbox environment?",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Tom Wilson",
        contact_email: "tom.wilson@dataflow.io",
      },
      {
        id: "msg-035",
        role: "assistant",
        content: "Absolutely! I can set up a sandbox environment for you. It includes full API access so you can test integrations. I'll send you the credentials once it's ready.",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "tom.wilson@dataflow.io",
      },
      {
        id: "msg-036",
        role: "system",
        content: "Sandbox environment created. Credentials sent via secure email.",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-037",
        role: "user",
        content: "Got the credentials, thanks! We'll start testing this week.",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Tom Wilson",
        contact_phone: "+1 (555) 789-0123",
      },
      {
        id: "msg-038",
        role: "assistant",
        content: "Perfect! Let me know if you run into any issues or have questions during testing. Happy to help!",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
    ],
  },
  "deal-007": {
    deal_id: "deal-007",
    deal_title: "CloudSync Technologies - Enterprise",
    contact_name: "Rachel Kim",
    contact_phone: "+1 (555) 890-1234",
    contact_email: "rachel.kim@cloudsync.tech",
    last_activity: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-034",
        role: "user",
        content: "Hi, we're looking for an enterprise solution that can handle our cloud infrastructure needs.",
        timestamp: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Rachel Kim",
        contact_email: "rachel.kim@cloudsync.tech",
      },
      {
        id: "msg-035",
        role: "assistant",
        content: "Hi Rachel! Our Enterprise solution is perfect for cloud infrastructure. It includes advanced security, compliance features, and seamless cloud integrations. What's your current infrastructure setup?",
        timestamp: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "rachel.kim@cloudsync.tech",
      },
      {
        id: "msg-036",
        role: "user",
        content: "We're using AWS and Azure. Do you support both?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Rachel Kim",
        contact_email: "rachel.kim@cloudsync.tech",
      },
      {
        id: "msg-037",
        role: "assistant",
        content: "Yes! We have native integrations for both AWS and Azure, plus multi-cloud support. I can send you a detailed integration guide. Would that be helpful?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "rachel.kim@cloudsync.tech",
      },
      {
        id: "msg-038",
        role: "user",
        content: "Yes, please send the guide. Also, do you support Kubernetes deployments?",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Rachel Kim",
        contact_email: "rachel.kim@cloudsync.tech",
      },
      {
        id: "msg-039",
        role: "assistant",
        content: "We absolutely support Kubernetes! I'll include that in the guide. We have Helm charts and detailed deployment docs. Perfect for cloud-native setups.",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "rachel.kim@cloudsync.tech",
      },
      {
        id: "msg-040",
        role: "system",
        content: "Email sent: Multi-Cloud Integration Guide with Kubernetes Deployment Instructions",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-041",
        role: "user",
        content: "This looks great! We'll review with our DevOps team. Can we schedule a technical deep-dive?",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Rachel Kim",
        contact_email: "rachel.kim@cloudsync.tech",
      },
      {
        id: "msg-042",
        role: "assistant",
        content: "Absolutely! I can set up a technical session with our solutions architect. What's the best time for your DevOps team?",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "rachel.kim@cloudsync.tech",
      },
    ],
  },
  "deal-008": {
    deal_id: "deal-008",
    deal_title: "NextGen Solutions - Premium",
    contact_name: "James Rodriguez",
    contact_phone: "+1 (555) 901-2345",
    contact_email: "james.r@nextgensolutions.com",
    last_activity: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-038",
        role: "user",
        content: "We're evaluating your Premium package. What's the onboarding process like?",
        timestamp: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "James Rodriguez",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-039",
        role: "assistant",
        content: "Hi James! Our Premium package includes white-glove onboarding with a dedicated specialist. Typically takes 2-3 weeks. We handle everything from setup to training. Want to schedule a call to discuss your timeline?",
        timestamp: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-040",
        role: "user",
        content: "That sounds good. Can you send me more details about the training?",
        timestamp: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "James Rodriguez",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-041",
        role: "user",
        content: "That would be great. What does the training include?",
        timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "James Rodriguez",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-042",
        role: "assistant",
        content: "The training includes: 1) Platform walkthrough, 2) Best practices session, 3) Q&A with your team, and 4) Custom training materials. We can tailor it to your needs.",
        timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-043",
        role: "system",
        content: "Call completed - Duration: 15 minutes. Discussed onboarding timeline and training options. Sent training materials via email.",
        timestamp: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-044",
        role: "user",
        content: "Thanks for the call! The training plan looks good. I'll share it with my team.",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "James Rodriguez",
        contact_email: "james.r@nextgensolutions.com",
      },
      {
        id: "msg-045",
        role: "assistant",
        content: "Perfect! Once your team reviews it, let's schedule the training sessions. I'm flexible on timing.",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "james.r@nextgensolutions.com",
      },
    ],
  },
  "deal-009": {
    deal_id: "deal-009",
    deal_title: "Velocity Partners - Growth Package",
    contact_name: "Amanda Foster",
    contact_phone: "+1 (555) 012-3456",
    contact_email: "amanda@velocitypartners.com",
    last_activity: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-042",
        role: "user",
        content: "We're a fast-growing company. Does the Growth Package scale with us?",
        timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Amanda Foster",
        contact_email: "amanda@velocitypartners.com",
      },
      {
        id: "msg-043",
        role: "assistant",
        content: "Absolutely! The Growth Package is designed to scale. It includes flexible user limits, usage-based pricing options, and priority support. Many companies start here and grow into Enterprise. Want to see how it scales?",
        timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "amanda@velocitypartners.com",
      },
      {
        id: "msg-044",
        role: "user",
        content: "Yes, that would be helpful. Also, what's the pricing structure?",
        timestamp: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Amanda Foster",
        contact_email: "amanda@velocitypartners.com",
      },
      {
        id: "msg-045",
        role: "assistant",
        content: "The Growth Package starts at $299/month for up to 25 users. As you scale, pricing adjusts based on usage. We also offer annual plans with 15% discount. I'll send you a detailed pricing sheet.",
        timestamp: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "amanda@velocitypartners.com",
      },
      {
        id: "msg-046",
        role: "system",
        content: "Email sent: Growth Package Pricing and Scaling Guide",
        timestamp: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-047",
        role: "user",
        content: "The pricing looks reasonable. Can we discuss custom terms for our specific needs?",
        timestamp: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Amanda Foster",
        contact_email: "amanda@velocitypartners.com",
      },
      {
        id: "msg-048",
        role: "assistant",
        content: "Absolutely! I'd be happy to discuss custom terms. What specific requirements do you have? We can schedule a call to go through everything.",
        timestamp: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "amanda@velocitypartners.com",
      },
    ],
  },
  "deal-010": {
    deal_id: "deal-010",
    deal_title: "PrimeTech Industries - Enterprise",
    contact_name: "Robert Chen",
    contact_phone: "+1 (555) 123-4567",
    contact_email: "robert.chen@primetech.com",
    last_activity: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-045",
        role: "user",
        content: "We need an enterprise solution with custom integrations. Is that possible?",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Robert Chen",
        contact_email: "robert.chen@primetech.com",
      },
      {
        id: "msg-046",
        role: "assistant",
        content: "Hi Robert! Yes, our Enterprise package includes custom integrations. We have a dedicated integration team that works with you to build exactly what you need. What systems are you looking to integrate?",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "robert.chen@primetech.com",
      },
      {
        id: "msg-047",
        role: "user",
        content: "We use Salesforce, HubSpot, and a custom ERP. Can you integrate with all of those?",
        timestamp: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Robert Chen",
        contact_email: "robert.chen@primetech.com",
      },
      {
        id: "msg-048",
        role: "assistant",
        content: "We have native integrations for Salesforce and HubSpot, and we can build custom integrations for your ERP. I'll connect you with our integration specialist. Sound good?",
        timestamp: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "robert.chen@primetech.com",
      },
      {
        id: "msg-049",
        role: "user",
        content: "That sounds perfect. When can we schedule that?",
        timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Robert Chen",
        contact_email: "robert.chen@primetech.com",
      },
      {
        id: "msg-050",
        role: "assistant",
        content: "I'll connect you with our integration specialist. They're available next week. I'll send you a calendar invite once confirmed.",
        timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "robert.chen@primetech.com",
      },
      {
        id: "msg-051",
        role: "system",
        content: "Call scheduled with integration specialist for next week",
        timestamp: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-052",
        role: "system",
        content: "Call completed - Duration: 35 minutes. Discussed custom integrations for Salesforce, HubSpot, and ERP. Technical requirements documented.",
        timestamp: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 123-4567",
      },
      {
        id: "msg-053",
        role: "user",
        content: "Great call! The integration plan looks solid. I'll review the technical specs with my team.",
        timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Robert Chen",
        contact_email: "robert.chen@primetech.com",
      },
      {
        id: "msg-054",
        role: "assistant",
        content: "Excellent! Let me know if your team has any questions about the technical specs. I'm here to help!",
        timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "robert.chen@primetech.com",
      },
    ],
  },
  "deal-011": {
    deal_id: "deal-011",
    deal_title: "Apex Digital - Starter Package",
    contact_name: "Chris Anderson",
    contact_phone: "+1 (555) 234-5678",
    contact_email: "chris@apexdigital.com",
    last_activity: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-050",
        role: "user",
        content: "I'm interested in the Starter Package. What's included?",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Chris Anderson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-051",
        role: "assistant",
        content: "Hi Chris! The Starter Package includes up to 5 users, core features, email support, and basic analytics. Perfect for small teams getting started. It's $99/month. Want to see a demo?",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000 + 2 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-052",
        role: "user",
        content: "That sounds reasonable. Can I try it first?",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Chris Anderson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-053",
        role: "assistant",
        content: "Absolutely! We offer a 14-day free trial with full access. No credit card required. I can set that up for you right now. Ready to get started?",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-054",
        role: "user",
        content: "Yes, let's do it!",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Chris Anderson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-055",
        role: "assistant",
        content: "Perfect! I've set up your trial account. Check your email for login credentials. I'll check in with you in a few days to see how it's going!",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "chris@apexdigital.com",
      },
      {
        id: "msg-056",
        role: "system",
        content: "Trial account created. Welcome email sent with login credentials.",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 11 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-057",
        role: "assistant",
        content: "Hey Chris! How's the trial going? Any questions so far?",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-058",
        role: "user",
        content: "It's going well! We're still exploring. I'll let you know if we have questions.",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Chris Anderson",
        contact_phone: "+1 (555) 234-5678",
      },
    ],
  },
  "deal-012": {
    deal_id: "deal-012",
    deal_title: "Summit Enterprises - Professional",
    contact_name: "Patricia Lee",
    contact_phone: "+1 (555) 345-6789",
    contact_email: "patricia.lee@summitenterprises.com",
    last_activity: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-054",
        role: "user",
        content: "We're looking at the Professional package. What makes it different from Premium?",
        timestamp: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Patricia Lee",
        contact_email: "patricia.lee@summitenterprises.com",
      },
      {
        id: "msg-055",
        role: "assistant",
        content: "Hi Patricia! The Professional package includes advanced features like custom workflows, API access, and priority support. Premium adds white-glove onboarding and dedicated account management. What's most important for Summit?",
        timestamp: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "patricia.lee@summitenterprises.com",
      },
      {
        id: "msg-056",
        role: "user",
        content: "API access is important. Can you tell me more about that?",
        timestamp: new Date(Date.now() - 41 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Patricia Lee",
        contact_email: "patricia.lee@summitenterprises.com",
      },
      {
        id: "msg-057",
        role: "assistant",
        content: "Our API is comprehensive and well-documented. It includes REST endpoints, webhooks, and SDKs for popular languages. Perfect for building custom integrations. Want to see the API docs?",
        timestamp: new Date(Date.now() - 41 * 24 * 60 * 60 * 1000 + 7 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "patricia.lee@summitenterprises.com",
      },
      {
        id: "msg-058",
        role: "user",
        content: "Yes, please send the API docs. Also, do you have rate limits?",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Patricia Lee",
        contact_email: "patricia.lee@summitenterprises.com",
      },
      {
        id: "msg-059",
        role: "assistant",
        content: "Great question! Professional package includes 10,000 API calls/month. Enterprise has unlimited. I'll send you the full API documentation with rate limit details.",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "patricia.lee@summitenterprises.com",
      },
      {
        id: "msg-060",
        role: "system",
        content: "Email sent: Complete API Documentation with Rate Limits and Best Practices",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-061",
        role: "user",
        content: "Thanks! The docs look good. We'll review and get back to you.",
        timestamp: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Patricia Lee",
        contact_email: "patricia.lee@summitenterprises.com",
      },
      {
        id: "msg-062",
        role: "assistant",
        content: "Perfect! Let me know if you have any questions. I'm here to help!",
        timestamp: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "patricia.lee@summitenterprises.com",
      },
    ],
  },
  "deal-013": {
    deal_id: "deal-013",
    deal_title: "MedTech Solutions - Enterprise",
    contact_name: "Dr. Emily Watson",
    contact_phone: "+1 (555) 456-7890",
    contact_email: "emily.watson@medtechsolutions.com",
    last_activity: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-060",
        role: "user",
        content: "We're a healthcare company. Do you have HIPAA compliance?",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Dr. Emily Watson",
        contact_email: "emily.watson@medtechsolutions.com",
      },
      {
        id: "msg-061",
        role: "assistant",
        content: "Hi Dr. Watson! Yes, we're HIPAA compliant and SOC 2 Type II certified. We have BAA agreements available and follow all healthcare data regulations. Would you like to see our compliance documentation?",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "emily.watson@medtechsolutions.com",
      },
      {
        id: "msg-062",
        role: "user",
        content: "Yes, that would be very helpful. Also, do you support HL7 integration?",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Dr. Emily Watson",
        contact_email: "emily.watson@medtechsolutions.com",
      },
      {
        id: "msg-063",
        role: "assistant",
        content: "We do support HL7 integration! I'll send you both the compliance docs and our HL7 integration guide. We've worked with many healthcare organizations.",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "emily.watson@medtechsolutions.com",
      },
      {
        id: "msg-064",
        role: "system",
        content: "Email sent: HIPAA Compliance Documentation and HL7 Integration Guide",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-065",
        role: "user",
        content: "The compliance docs look good. Can we schedule a call to discuss implementation?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Dr. Emily Watson",
        contact_email: "emily.watson@medtechsolutions.com",
      },
      {
        id: "msg-066",
        role: "assistant",
        content: "Absolutely! I'll send you a calendar invite. We can discuss your specific healthcare use case and implementation timeline.",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "emily.watson@medtechsolutions.com",
      },
      {
        id: "msg-067",
        role: "system",
        content: "Call completed - Duration: 40 minutes. Discussed HIPAA compliance, HL7 integration, and healthcare-specific requirements. Implementation plan shared.",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 456-7890",
      },
      {
        id: "msg-068",
        role: "assistant",
        content: "Hi Dr. Watson, just following up on our call. Did you have a chance to review the implementation plan?",
        timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "emily.watson@medtechsolutions.com",
      },
    ],
  },
  "deal-014": {
    deal_id: "deal-014",
    deal_title: "FinTech Innovations - Premium",
    contact_name: "Michael Brown",
    contact_phone: "+1 (555) 567-8901",
    contact_email: "michael.brown@fintechinnovations.com",
    last_activity: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-065",
        role: "user",
        content: "We're a fintech company. Security is our top priority. What security features do you offer?",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Michael Brown",
        contact_email: "michael.brown@fintechinnovations.com",
      },
      {
        id: "msg-066",
        role: "assistant",
        content: "Hi Michael! Security is our top priority too. We offer end-to-end encryption, SSO, MFA, audit logs, and we're PCI DSS Level 1 compliant. We also have SOC 2 Type II and ISO 27001 certifications. Want to see our security whitepaper?",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "michael.brown@fintechinnovations.com",
      },
      {
        id: "msg-067",
        role: "user",
        content: "Yes, please send the whitepaper. Also, do you have penetration testing reports?",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Michael Brown",
        contact_email: "michael.brown@fintechinnovations.com",
      },
      {
        id: "msg-068",
        role: "assistant",
        content: "We conduct regular penetration testing and can share our latest reports under NDA. I'll send you the security whitepaper and we can discuss the pen test reports on a call.",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "michael.brown@fintechinnovations.com",
      },
      {
        id: "msg-069",
        role: "system",
        content: "Email sent: Security Whitepaper and Compliance Certifications",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 7 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-070",
        role: "user",
        content: "The security documentation looks comprehensive. Can we schedule a security review call?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Michael Brown",
        contact_email: "michael.brown@fintechinnovations.com",
      },
      {
        id: "msg-071",
        role: "assistant",
        content: "Absolutely! I'll set up a call with our security team. They can walk you through all our security measures and answer any questions.",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "michael.brown@fintechinnovations.com",
      },
      {
        id: "msg-072",
        role: "system",
        content: "Call completed - Duration: 45 minutes. Security team reviewed all security features, compliance certifications, and answered technical questions. NDA signed for pen test reports.",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-073",
        role: "assistant",
        content: "Hi Michael, just checking in. How did the security review go with your team?",
        timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "michael.brown@fintechinnovations.com",
      },
    ],
  },
  "deal-015": {
    deal_id: "deal-015",
    deal_title: "EduTech Academy - Growth Package",
    contact_name: "Jessica Taylor",
    contact_phone: "+1 (555) 678-9012",
    contact_email: "jessica.taylor@edutechacademy.com",
    last_activity: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-070",
        role: "user",
        content: "We're an online education platform. Do you support learning management system integrations?",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Jessica Taylor",
        contact_phone: "+1 (555) 678-9012",
      },
      {
        id: "msg-071",
        role: "assistant",
        content: "Hi Jessica! Yes, we integrate with popular LMS platforms like Canvas, Moodle, and Blackboard. We also support SCORM and xAPI standards. What LMS are you using?",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-072",
        role: "user",
        content: "We use Canvas. Can you show me how the integration works?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Jessica Taylor",
        contact_phone: "+1 (555) 678-9012",
      },
      {
        id: "msg-073",
        role: "assistant",
        content: "Absolutely! I can set up a demo showing the Canvas integration. It's seamless - students can access everything from their Canvas dashboard. Want to schedule a demo?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-074",
        role: "user",
        content: "Yes, that would be great! This week works for me.",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Jessica Taylor",
        contact_phone: "+1 (555) 678-9012",
      },
      {
        id: "msg-075",
        role: "assistant",
        content: "Perfect! I'll send you a calendar invite with a few time options. Looking forward to showing you the integration!",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000 + 2 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-076",
        role: "system",
        content: "Demo completed - Duration: 25 minutes. Showed Canvas integration, SCORM support, and student dashboard features. Follow-up materials sent.",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 678-9012",
      },
      {
        id: "msg-077",
        role: "user",
        content: "The demo was great! We're interested. Can you send pricing for our student count?",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jessica Taylor",
        contact_email: "jessica.taylor@edutechacademy.com",
      },
      {
        id: "msg-078",
        role: "assistant",
        content: "Absolutely! What's your current student count? I'll prepare a custom quote based on that.",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "jessica.taylor@edutechacademy.com",
      },
      {
        id: "msg-079",
        role: "user",
        content: "We have about 5,000 active students currently, but we're growing fast.",
        timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jessica Taylor",
        contact_email: "jessica.taylor@edutechacademy.com",
      },
      {
        id: "msg-080",
        role: "assistant",
        content: "Perfect! I'll create a quote that scales with your growth. The Growth Package is ideal for your situation. I'll send it over today.",
        timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "jessica.taylor@edutechacademy.com",
      },
      {
        id: "msg-081",
        role: "assistant",
        content: "Hi Jessica, just checking in on the quote. Have you had a chance to review it?",
        timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "jessica.taylor@edutechacademy.com",
      },
    ],
  },
  "deal-016": {
    deal_id: "deal-016",
    deal_title: "RetailMax Corp - Professional",
    contact_name: "Daniel Kim",
    contact_phone: "+1 (555) 789-0123",
    contact_email: "daniel.kim@retailmax.com",
    last_activity: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-075",
        role: "user",
        content: "We're a retail chain. Do you integrate with POS systems?",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Daniel Kim",
        contact_email: "daniel.kim@retailmax.com",
      },
      {
        id: "msg-076",
        role: "assistant",
        content: "Hi Daniel! Yes, we integrate with major POS systems including Square, Shopify, and custom solutions. We can sync inventory, sales data, and customer information in real-time. Which POS system are you using?",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "daniel.kim@retailmax.com",
      },
      {
        id: "msg-077",
        role: "user",
        content: "We use Square. Can you show me how the integration works?",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Daniel Kim",
        contact_email: "daniel.kim@retailmax.com",
      },
      {
        id: "msg-078",
        role: "assistant",
        content: "Absolutely! Square integration is one of our most popular. I can set up a demo showing real-time sync, inventory management, and customer data flow. Want to schedule that?",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "daniel.kim@retailmax.com",
      },
      {
        id: "msg-079",
        role: "user",
        content: "Yes, let's do it. I'm available this week.",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Daniel Kim",
        contact_email: "daniel.kim@retailmax.com",
      },
      {
        id: "msg-080",
        role: "system",
        content: "Demo completed - Duration: 30 minutes. Showed Square POS integration, inventory sync, and customer data management. Integration guide sent.",
        timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 789-0123",
      },
      {
        id: "msg-081",
        role: "user",
        content: "The demo was impressive! How long does the integration take?",
        timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Daniel Kim",
        contact_email: "daniel.kim@retailmax.com",
      },
      {
        id: "msg-082",
        role: "assistant",
        content: "Square integration typically takes 1-2 days to set up. We handle the technical side, and you just need to authorize the connection. Very straightforward!",
        timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "daniel.kim@retailmax.com",
      },
      {
        id: "msg-083",
        role: "assistant",
        content: "Hi Daniel, just checking in. Have you had a chance to discuss the Square integration with your team?",
        timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "daniel.kim@retailmax.com",
      },
    ],
  },
  "deal-017": {
    deal_id: "deal-017",
    deal_title: "GreenEnergy Solutions - Starter Package",
    contact_name: "Maria Garcia",
    contact_phone: "+1 (555) 890-1234",
    contact_email: "maria.garcia@greenenergy.com",
    last_activity: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-080",
        role: "user",
        content: "Hi! I'm interested in the Starter Package. Do you offer a free trial?",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Maria Garcia",
        contact_phone: "+1 (555) 890-1234",
      },
      {
        id: "msg-081",
        role: "assistant",
        content: "Hi Maria! Yes, we offer a 14-day free trial with full access. No credit card required. I can set that up for you right now. Ready to get started?",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 2 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-082",
        role: "user",
        content: "That sounds perfect! Let's do it.",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Maria Garcia",
        contact_phone: "+1 (555) 890-1234",
      },
      {
        id: "msg-083",
        role: "assistant",
        content: "Great! I've set up your trial account. Check your email for login credentials. I'll check in with you in a few days to see how it's going!",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 7 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "maria.garcia@greenenergy.com",
      },
      {
        id: "msg-084",
        role: "system",
        content: "Trial account created. Welcome email sent with login credentials and getting started guide.",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-085",
        role: "assistant",
        content: "Hey Maria! How's the trial going? Any questions so far?",
        timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-086",
        role: "user",
        content: "It's going well! We're still exploring the features. I'll let you know if we have questions.",
        timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Maria Garcia",
        contact_phone: "+1 (555) 890-1234",
      },
      {
        id: "msg-087",
        role: "assistant",
        content: "Perfect! Don't hesitate to reach out if you need anything. I'm here to help!",
        timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-088",
        role: "assistant",
        content: "Hi Maria, your trial is ending soon. How's everything going? Would you like to continue with the Starter Package?",
        timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "maria.garcia@greenenergy.com",
      },
    ],
  },
  "deal-018": {
    deal_id: "deal-018",
    deal_title: "Logistics Pro - Enterprise",
    contact_name: "Kevin Nguyen",
    contact_phone: "+1 (555) 901-2345",
    contact_email: "kevin.nguyen@logisticspro.com",
    last_activity: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-085",
        role: "user",
        content: "We're a logistics company. Do you integrate with shipping carriers like FedEx and UPS?",
        timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Kevin Nguyen",
        contact_email: "kevin.nguyen@logisticspro.com",
      },
      {
        id: "msg-086",
        role: "assistant",
        content: "Hi Kevin! Yes, we have native integrations with FedEx, UPS, DHL, and USPS. You can track shipments, print labels, and manage everything from one place. Which carriers do you use most?",
        timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "kevin.nguyen@logisticspro.com",
      },
      {
        id: "msg-087",
        role: "user",
        content: "We use FedEx and UPS primarily. Can you show me the integration?",
        timestamp: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Kevin Nguyen",
        contact_email: "kevin.nguyen@logisticspro.com",
      },
      {
        id: "msg-088",
        role: "assistant",
        content: "Absolutely! I can set up a demo showing label printing, tracking, and rate comparison between carriers. Want to schedule that?",
        timestamp: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "kevin.nguyen@logisticspro.com",
      },
      {
        id: "msg-089",
        role: "system",
        content: "Demo completed - Duration: 35 minutes. Showed FedEx and UPS integrations, label printing, tracking, and rate comparison features. Integration guide sent.",
        timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-090",
        role: "user",
        content: "The demo was great! How quickly can we get this set up?",
        timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Kevin Nguyen",
        contact_email: "kevin.nguyen@logisticspro.com",
      },
      {
        id: "msg-091",
        role: "assistant",
        content: "Carrier integrations typically take 2-3 business days. We'll need your carrier account credentials and then we handle the rest. Very quick setup!",
        timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "kevin.nguyen@logisticspro.com",
      },
      {
        id: "msg-092",
        role: "assistant",
        content: "Hi Kevin, just checking in. Have you had a chance to discuss the carrier integrations with your team?",
        timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "kevin.nguyen@logisticspro.com",
      },
    ],
  },
}

export function getConversationForDeal(dealId: string): DealConversation | null {
  return demoConversations[dealId] || null
}
