// Demo conversation data for MVP
// Structured to match GoHighLevel API response format

export interface ConversationMessage {
  id: string
  role: "user" | "assistant" | "system"
  content: string
  timestamp: string
  type?: "sms" | "email" | "call" | "note"
  direction?: "inbound" | "outbound"
  contact_name?: string
  contact_phone?: string
  contact_email?: string
}

export interface DealConversation {
  deal_id: string
  deal_title: string
  contact_name: string
  contact_phone?: string
  contact_email?: string
  messages: ConversationMessage[]
  last_activity: string
}

export const demoConversations: Record<string, DealConversation> = {
  "deal-001": {
    deal_id: "deal-001",
    deal_title: "Sarah Johnson - Real Estate Mastery Program",
    contact_name: "Sarah Johnson",
    contact_phone: "+1 (555) 234-5678",
    contact_email: "sarah.johnson82@gmail.com",
    last_activity: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-001",
        role: "user",
        content: "Hey! I saw your program online and I'm really interested. I've been wanting to get into real estate investing but honestly don't know where to start. Can you tell me more?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Sarah Johnson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-002",
        role: "assistant",
        content: "Hi Sarah! So excited you're interested! Our Real Estate Mastery Program is perfect for beginners. We cover everything from finding deals to financing to managing properties. I can send you a free guide that walks through the basics. What's your email?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-003",
        role: "user",
        content: "That would be amazing! My email is sarah.johnson82@gmail.com. I'm especially curious about how to find good deals without a ton of cash upfront.",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Sarah Johnson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-004",
        role: "assistant",
        content: "Perfect! I just sent it over. And great question about finding deals - that's actually one of the first things we cover! There are so many creative strategies that don't require a huge down payment. The guide I sent has some examples, but we go way deeper in the program.",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "sarah.johnson82@gmail.com",
      },
      {
        id: "msg-005",
        role: "user",
        content: "Got it, thanks! I'll read through it this weekend. The program sounds really comprehensive.",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Sarah Johnson",
        contact_email: "sarah.johnson82@gmail.com",
      },
      {
        id: "msg-006",
        role: "assistant",
        content: "Awesome! Let me know what you think after you read it. I'm here if you have any questions!",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "sarah.johnson82@gmail.com",
      },
      {
        id: "msg-007",
        role: "system",
        content: "Email sent: Real Estate Investing Starter Guide",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 16 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-008",
        role: "assistant",
        content: "Hey Sarah! Just checking in - did you get a chance to read through the guide? I'd love to hear your thoughts and see if the program might be a good fit for you!",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "sarah.johnson82@gmail.com",
      },
      {
        id: "msg-009",
        role: "user",
        content: "Hi! Yeah I read it, it was really helpful. I'm still thinking it over though. The program sounds great but I want to make sure I'm ready to commit. Can I ask a few questions?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Sarah Johnson",
        contact_email: "sarah.johnson82@gmail.com",
      },
      {
        id: "msg-010",
        role: "assistant",
        content: "Of course! Ask away - I'm here to help you figure out if it's the right fit. What's on your mind?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "sarah.johnson82@gmail.com",
      },
      {
        id: "msg-011",
        role: "system",
        content: "Call attempted - No answer. Left voicemail.",
        timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-012",
        role: "assistant",
        content: "Hey Sarah! Just wanted to follow up - I know you had some questions. Would love to chat when you have a minute!",
        timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-013",
        role: "system",
        content: "Email sent: Program details and FAQ",
        timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
    ],
  },
  "deal-002": {
    deal_id: "deal-002",
    deal_title: "Mike Chen - Real Estate Mastery Program",
    contact_name: "Mike Chen",
    contact_phone: "+1 (555) 345-6789",
    contact_email: "mikechen.realestate@gmail.com",
    last_activity: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-009",
        role: "user",
        content: "Hey! I've been following your content for a while and I'm really interested in the program. I'm a complete beginner though - is it still a good fit?",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Mike Chen",
        contact_phone: "+1 (555) 345-6789",
      },
      {
        id: "msg-010",
        role: "assistant",
        content: "Hi Mike! Absolutely - we actually have a lot of students who start with zero experience! The program is designed to take you from beginner to closing your first deal. We cover everything step by step. Want to hop on a quick call so I can answer your questions?",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-011",
        role: "user",
        content: "Yeah that would be great! I'm free Tuesday or Wednesday afternoon if either of those work?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Mike Chen",
        contact_phone: "+1 (555) 345-6789",
      },
      {
        id: "msg-012",
        role: "assistant",
        content: "Perfect! Tuesday at 2pm works great for me. I'll send you a calendar invite. Looking forward to chatting!",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-013",
        role: "user",
        content: "Sounds good, see you then!",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Mike Chen",
        contact_phone: "+1 (555) 345-6789",
      },
      {
        id: "msg-014",
        role: "system",
        content: "Call completed - Duration: 25 minutes. Discussed program structure, pricing, and answered beginner questions. Mike seemed very interested.",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 345-6789",
      },
      {
        id: "msg-015",
        role: "user",
        content: "Thanks so much for the call! I really appreciate you taking the time. I'm going to think it over and talk to my wife about it.",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Mike Chen",
        contact_email: "mikechen.realestate@gmail.com",
      },
      {
        id: "msg-016",
        role: "assistant",
        content: "Of course! Take your time - it's a big decision. I sent you the program details and pricing to your email. Let me know if you or your wife have any questions!",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 1 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "mikechen.realestate@gmail.com",
      },
      {
        id: "msg-017",
        role: "assistant",
        content: "Hey Mike! Just wanted to check in - have you and your wife had a chance to talk about the program? Happy to answer any questions if they came up!",
        timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
    ],
  },
  "deal-003": {
    deal_id: "deal-003",
    deal_title: "Jennifer Martinez - Real Estate Mastery Program",
    contact_name: "Jennifer Martinez",
    contact_phone: "+1 (555) 456-7890",
    contact_email: "jennifer.martinez.re@gmail.com",
    last_activity: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-015",
        role: "user",
        content: "Hi! I've been watching your videos and I'm really interested in learning real estate investing. I work full time though - is the program flexible enough for someone with a busy schedule?",
        timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jennifer Martinez",
        contact_email: "jennifer.martinez.re@gmail.com",
      },
      {
        id: "msg-016",
        role: "assistant",
        content: "Hi Jennifer! Great question - most of our students work full time jobs! The program is designed to be flexible. You can go through the modules at your own pace, and we have live Q&A sessions in the evenings and weekends. Plus everything is recorded so you never miss anything.",
        timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "jennifer.martinez.re@gmail.com",
      },
      {
        id: "msg-017",
        role: "user",
        content: "That sounds perfect! I'm definitely interested. Can you send me more info about pricing and what's included?",
        timestamp: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jennifer Martinez",
        contact_email: "jennifer.martinez.re@gmail.com",
      },
      {
        id: "msg-018",
        role: "assistant",
        content: "Absolutely! I'll send you the full program breakdown with pricing. It includes all the training modules, access to our private community, templates and checklists, plus ongoing support. I'll get that to you right now!",
        timestamp: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "jennifer.martinez.re@gmail.com",
      },
      {
        id: "msg-019",
        role: "user",
        content: "Thanks! I got it. The pricing is a bit more than I expected but I can see the value. I need to think about it and maybe talk to my husband.",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jennifer Martinez",
        contact_email: "jennifer.martinez.re@gmail.com",
      },
      {
        id: "msg-020",
        role: "assistant",
        content: "Totally understand - it's an investment in your future! I know it can feel like a lot upfront, but most of our students make that back with their first deal. Happy to answer any questions you or your husband have. Take your time!",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "jennifer.martinez.re@gmail.com",
      },
      {
        id: "msg-021",
        role: "system",
        content: "Call scheduled for tomorrow at 7 PM to discuss program details",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-022",
        role: "system",
        content: "Call completed - Duration: 35 minutes. Discussed program structure, answered questions about time commitment, and shared success stories. Jennifer and her husband seemed very interested.",
        timestamp: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 456-7890",
      },
      {
        id: "msg-023",
        role: "user",
        content: "Thanks so much for the call! We really appreciated you taking the time. We're going to sleep on it and let you know.",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jennifer Martinez",
        contact_email: "jennifer.martinez.re@gmail.com",
      },
      {
        id: "msg-024",
        role: "assistant",
        content: "Of course! Take your time - it's a big decision. I'm here whenever you're ready. Feel free to reach out with any other questions!",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "jennifer.martinez.re@gmail.com",
      },
    ],
  },
  "deal-004": {
    deal_id: "deal-004",
    deal_title: "David Park - Real Estate Mastery Program",
    contact_name: "David Park",
    contact_phone: "+1 (555) 567-8901",
    contact_email: "david.park.investor@gmail.com",
    last_activity: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-020",
        role: "user",
        content: "Hey! I've been thinking about getting into real estate investing for a while now. I saw your program and it looks really comprehensive. Do you have payment plans available?",
        timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "David Park",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-021",
        role: "assistant",
        content: "Hi David! Yes, we do offer payment plans! We have a few options - you can split it into 3 or 6 monthly payments, no interest. Makes it way more manageable. Which option are you thinking?",
        timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000 + 4 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-022",
        role: "user",
        content: "The 6 month plan sounds good. How does that work exactly?",
        timestamp: new Date(Date.now() - 34 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "David Park",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-023",
        role: "assistant",
        content: "Super simple! You pay the first payment when you enroll, then we automatically charge the remaining 5 payments monthly. You get full access to everything right away. No hidden fees or anything like that.",
        timestamp: new Date(Date.now() - 34 * 24 * 60 * 60 * 1000 + 6 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-024",
        role: "user",
        content: "Perfect! That works for me. Can I start right away or do I need to wait?",
        timestamp: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "David Park",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-025",
        role: "assistant",
        content: "You can start immediately! As soon as you enroll, you'll get instant access to all the modules, the community, everything. Most people start diving in the same day. Want me to send you the enrollment link?",
        timestamp: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-026",
        role: "system",
        content: "Call completed - Duration: 15 minutes. Discussed payment plan options and enrollment process. David seemed ready to enroll.",
        timestamp: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-027",
        role: "user",
        content: "Hey! I got the link but I want to think about it one more night. Is that cool?",
        timestamp: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "David Park",
        contact_email: "david.park.investor@gmail.com",
      },
      {
        id: "msg-028",
        role: "assistant",
        content: "Absolutely! Take your time - no pressure at all. The link will be good whenever you're ready. Let me know if you have any other questions!",
        timestamp: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "david.park.investor@gmail.com",
      },
      {
        id: "msg-029",
        role: "assistant",
        content: "Hey David! Just wanted to check in - did you decide if the program is right for you? Happy to answer any questions!",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
    ],
  },
  "deal-005": {
    deal_id: "deal-005",
    deal_title: "Lisa Thompson - Real Estate Mastery Program",
    contact_name: "Lisa Thompson",
    contact_phone: "+1 (555) 678-9012",
    contact_email: "lisathompson.re@gmail.com",
    last_activity: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-025",
        role: "user",
        content: "Hi! I've been following your Instagram and I'm really interested in your program. I have some experience with real estate already - I own one rental property. Would this still be valuable for me?",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Lisa Thompson",
        contact_email: "lisathompson.re@gmail.com",
      },
      {
        id: "msg-026",
        role: "assistant",
        content: "Hi Lisa! That's awesome that you already have a rental! The program is definitely still valuable - we cover scaling strategies, finding more deals, advanced financing, and building a portfolio. A lot of students come in with one property and leave with 5-10. Want to chat about your goals?",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "lisathompson.re@gmail.com",
      },
      {
        id: "msg-027",
        role: "user",
        content: "Yes that would be great! I'd love to scale up but honestly I'm not sure the best way to do it. I'm free Tuesday or Wednesday afternoon if you have time?",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Lisa Thompson",
        contact_email: "lisathompson.re@gmail.com",
      },
      {
        id: "msg-028",
        role: "assistant",
        content: "Perfect! Tuesday at 2pm works great. I'll send you a calendar invite. Looking forward to chatting about how we can help you scale your portfolio!",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "lisathompson.re@gmail.com",
      },
      {
        id: "msg-029",
        role: "user",
        content: "Sounds good, see you then!",
        timestamp: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Lisa Thompson",
        contact_email: "lisathompson.re@gmail.com",
      },
      {
        id: "msg-030",
        role: "system",
        content: "Call completed - Duration: 40 minutes. Discussed scaling strategies, financing options, and portfolio building. Lisa was very engaged and asked great questions.",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 678-9012",
      },
      {
        id: "msg-031",
        role: "user",
        content: "Thanks so much for the call! I learned a lot. I'm going to think it over and talk to my husband about it. The program sounds really comprehensive.",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Lisa Thompson",
        contact_email: "lisathompson.re@gmail.com",
      },
      {
        id: "msg-032",
        role: "assistant",
        content: "You're so welcome! I'm glad it was helpful. Take your time - it's a big decision. Feel free to reach out if you or your husband have any questions!",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "lisathompson.re@gmail.com",
      },
    ],
  },
  "deal-006": {
    deal_id: "deal-006",
    deal_title: "Tom Wilson - Real Estate Mastery Program",
    contact_name: "Tom Wilson",
    contact_phone: "+1 (555) 789-0123",
    contact_email: "tomwilson.invest@gmail.com",
    last_activity: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-029",
        role: "user",
        content: "Hey! I saw your program and I'm really interested. I've been trying to learn real estate investing on my own but honestly I'm getting overwhelmed with all the info out there. Is your program good for someone like me?",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Tom Wilson",
        contact_phone: "+1 (555) 789-0123",
      },
      {
        id: "msg-030",
        role: "assistant",
        content: "Hi Tom! I totally get that - there's SO much info out there and it can be really overwhelming. That's exactly why we created this program! We break everything down step by step, in the right order, so you're not drowning in information. It's designed for people just like you.",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-031",
        role: "user",
        content: "That sounds perfect honestly. How long does it take to go through? I don't want to rush but also don't want it to drag on forever.",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Tom Wilson",
        contact_phone: "+1 (555) 789-0123",
      },
      {
        id: "msg-032",
        role: "assistant",
        content: "Great question! Most people go through the core content in 6-8 weeks if they're doing it part-time. But you have lifetime access, so you can go at your own pace. Some people finish faster, some take longer - totally up to you!",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-033",
        role: "system",
        content: "Email sent: Program Overview and Curriculum Guide",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-034",
        role: "user",
        content: "Got it, thanks! The curriculum looks really thorough. I'm going to read through everything and get back to you.",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Tom Wilson",
        contact_email: "tomwilson.invest@gmail.com",
      },
      {
        id: "msg-035",
        role: "assistant",
        content: "Awesome! Take your time. Let me know if you have any questions as you're reading through it. I'm here to help!",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "tomwilson.invest@gmail.com",
      },
      {
        id: "msg-036",
        role: "system",
        content: "Email sent: Success stories and student testimonials",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-037",
        role: "user",
        content: "Thanks for sending those! The success stories are really inspiring. I'm definitely leaning towards joining.",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Tom Wilson",
        contact_phone: "+1 (555) 789-0123",
      },
      {
        id: "msg-038",
        role: "assistant",
        content: "That's so great to hear! I'm excited for you. Let me know when you're ready or if you have any other questions!",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
    ],
  },
  "deal-007": {
    deal_id: "deal-007",
    deal_title: "Rachel Kim - Real Estate Mastery Program",
    contact_name: "Rachel Kim",
    contact_phone: "+1 (555) 890-1234",
    contact_email: "rachel.kim.invest@gmail.com",
    last_activity: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-034",
        role: "user",
        content: "Hi! I've been thinking about getting into real estate investing for a while. I'm a nurse and work crazy hours, so I'm worried I won't have time. Is this something I can actually do?",
        timestamp: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Rachel Kim",
        contact_email: "rachel.kim.invest@gmail.com",
      },
      {
        id: "msg-035",
        role: "assistant",
        content: "Hi Rachel! I totally understand that concern - and honestly, we have a lot of students with demanding jobs like nursing! The beauty of real estate investing is that once you get systems in place, it doesn't require a ton of your time. Plus the program is self-paced so you can fit it around your schedule. Want to chat about how it could work for you?",
        timestamp: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "rachel.kim.invest@gmail.com",
      },
      {
        id: "msg-036",
        role: "user",
        content: "That would be really helpful! I'm free most evenings after 7pm or weekends. Does that work?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Rachel Kim",
        contact_email: "rachel.kim.invest@gmail.com",
      },
      {
        id: "msg-037",
        role: "assistant",
        content: "Absolutely! I can do evenings or weekends - whatever works better for you. How about this Saturday at 10am? Or if you prefer evening, I can do Monday at 7:30pm.",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "rachel.kim.invest@gmail.com",
      },
      {
        id: "msg-038",
        role: "user",
        content: "Saturday at 10am works perfect! I'll be there.",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Rachel Kim",
        contact_email: "rachel.kim.invest@gmail.com",
      },
      {
        id: "msg-039",
        role: "assistant",
        content: "Perfect! I'll send you a calendar invite with the Zoom link. Looking forward to chatting with you!",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "rachel.kim.invest@gmail.com",
      },
      {
        id: "msg-040",
        role: "system",
        content: "Call completed - Duration: 35 minutes. Discussed time management strategies, program structure, and how to fit real estate investing around a demanding work schedule. Rachel seemed very interested.",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 890-1234",
      },
      {
        id: "msg-041",
        role: "user",
        content: "Thanks so much for the call! You really put my mind at ease about the time commitment. I'm going to think it over this week.",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Rachel Kim",
        contact_email: "rachel.kim.invest@gmail.com",
      },
      {
        id: "msg-042",
        role: "assistant",
        content: "You're so welcome! I'm glad I could help. Take your time - no rush at all. Let me know if you have any other questions!",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "rachel.kim.invest@gmail.com",
      },
    ],
  },
  "deal-008": {
    deal_id: "deal-008",
    deal_title: "James Rodriguez - Real Estate Mastery Program",
    contact_name: "James Rodriguez",
    contact_phone: "+1 (555) 901-2345",
    contact_email: "james.rodriguez.invest@gmail.com",
    last_activity: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-038",
        role: "user",
        content: "Hey! I've been looking into real estate investing and your program keeps coming up. I'm a teacher and don't have a huge budget - is this still realistic for me?",
        timestamp: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "James Rodriguez",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-039",
        role: "assistant",
        content: "Hi James! Absolutely - we have students from all different financial situations! The program teaches strategies that work whether you have $5k or $50k to start. Plus we cover creative financing so you don't need a ton of cash upfront. Want to hop on a quick call so I can show you how it works?",
        timestamp: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-040",
        role: "user",
        content: "Yeah that would be really helpful! I'm free most evenings after 5pm.",
        timestamp: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "James Rodriguez",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-041",
        role: "user",
        content: "Actually can we do tomorrow evening? Around 6:30?",
        timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "James Rodriguez",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-042",
        role: "assistant",
        content: "Perfect! Tomorrow at 6:30pm works great. I'll send you a calendar invite with the Zoom link. Looking forward to chatting!",
        timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-043",
        role: "system",
        content: "Call completed - Duration: 25 minutes. Discussed low-budget strategies, creative financing options, and how to get started with limited capital. James seemed very interested.",
        timestamp: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-044",
        role: "user",
        content: "Thanks so much for the call! You really helped me see how this could work for me. I'm going to think it over and talk to my wife about it.",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "James Rodriguez",
        contact_email: "james.rodriguez.invest@gmail.com",
      },
      {
        id: "msg-045",
        role: "assistant",
        content: "You're so welcome! I'm glad it was helpful. Take your time - it's a big decision. Feel free to reach out if you or your wife have any questions!",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "james.rodriguez.invest@gmail.com",
      },
    ],
  },
  "deal-009": {
    deal_id: "deal-009",
    deal_title: "Amanda Foster - Real Estate Mastery Program",
    contact_name: "Amanda Foster",
    contact_phone: "+1 (555) 012-3456",
    contact_email: "amanda.foster.re@gmail.com",
    last_activity: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-042",
        role: "user",
        content: "Hi! I've been following your content for a few months and I'm really interested in the program. I'm a stay-at-home mom and want to build something for my family's future. Is this something I can do part-time?",
        timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Amanda Foster",
        contact_email: "amanda.foster.re@gmail.com",
      },
      {
        id: "msg-043",
        role: "assistant",
        content: "Hi Amanda! That's so awesome that you want to build something for your family! And yes, absolutely - real estate investing is perfect for part-time. A lot of our students are stay-at-home parents. You can work on it during nap time, evenings, whenever works. The program is designed to fit around your schedule. Want to chat about how it could work for you?",
        timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "amanda.foster.re@gmail.com",
      },
      {
        id: "msg-044",
        role: "user",
        content: "That sounds perfect! I'd love to chat. I'm free most mornings after I drop the kids off at school, or during their nap time around 1pm.",
        timestamp: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Amanda Foster",
        contact_email: "amanda.foster.re@gmail.com",
      },
      {
        id: "msg-045",
        role: "assistant",
        content: "Perfect! How about tomorrow at 1pm? That way you can do it during nap time. I'll send you a calendar invite with the Zoom link!",
        timestamp: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "amanda.foster.re@gmail.com",
      },
      {
        id: "msg-046",
        role: "system",
        content: "Call scheduled for tomorrow at 1 PM",
        timestamp: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-047",
        role: "user",
        content: "Perfect! I'll be there. Thanks so much for being flexible with the timing!",
        timestamp: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Amanda Foster",
        contact_email: "amanda.foster.re@gmail.com",
      },
      {
        id: "msg-048",
        role: "assistant",
        content: "Of course! I totally get it - being a mom is a full-time job! Looking forward to chatting with you tomorrow!",
        timestamp: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "amanda.foster.re@gmail.com",
      },
    ],
  },
  "deal-010": {
    deal_id: "deal-010",
    deal_title: "Robert Chen - Real Estate Mastery Program",
    contact_name: "Robert Chen",
    contact_phone: "+1 (555) 123-4567",
    contact_email: "robert.chen.invest@gmail.com",
    last_activity: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-045",
        role: "user",
        content: "Hey! I've been watching your YouTube videos and I'm really interested in the program. I'm 28 and work in tech, but I want to start building passive income. Is this realistic for someone my age?",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Robert Chen",
        contact_email: "robert.chen.invest@gmail.com",
      },
      {
        id: "msg-046",
        role: "assistant",
        content: "Hi Robert! That's awesome that you're thinking about this early - you're actually in a perfect position! Starting in your 20s gives you so much time to build wealth. We have tons of students your age who are crushing it. The program is definitely realistic for you. Want to chat about your goals?",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "robert.chen.invest@gmail.com",
      },
      {
        id: "msg-047",
        role: "user",
        content: "Yeah that would be great! I'm really focused on building passive income so I can eventually quit my job. Is that realistic?",
        timestamp: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Robert Chen",
        contact_email: "robert.chen.invest@gmail.com",
      },
      {
        id: "msg-048",
        role: "assistant",
        content: "Absolutely! That's actually one of the most common goals we hear. Real estate is perfect for building passive income - once you have a few properties, the cash flow can replace your salary. We cover exactly how to do that in the program. Want to schedule a call so I can show you the numbers?",
        timestamp: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "robert.chen.invest@gmail.com",
      },
      {
        id: "msg-049",
        role: "user",
        content: "Yes! That would be amazing. I'm free most evenings after 6pm or weekends.",
        timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Robert Chen",
        contact_email: "robert.chen.invest@gmail.com",
      },
      {
        id: "msg-050",
        role: "assistant",
        content: "Perfect! How about this Saturday at 11am? I'll send you a calendar invite with the Zoom link.",
        timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "robert.chen.invest@gmail.com",
      },
      {
        id: "msg-051",
        role: "system",
        content: "Call scheduled for Saturday at 11 AM",
        timestamp: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-052",
        role: "system",
        content: "Call completed - Duration: 40 minutes. Discussed passive income strategies, timeline to financial freedom, and how to build a portfolio. Robert was very engaged and asked great questions.",
        timestamp: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 123-4567",
      },
      {
        id: "msg-053",
        role: "user",
        content: "Thanks so much for the call! You really helped me see the path forward. I'm going to think it over this week and let you know.",
        timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Robert Chen",
        contact_email: "robert.chen.invest@gmail.com",
      },
      {
        id: "msg-054",
        role: "assistant",
        content: "You're so welcome! I'm excited for you - you're in a great position to build something amazing. Take your time, and let me know if you have any other questions!",
        timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "robert.chen.invest@gmail.com",
      },
    ],
  },
  "deal-011": {
    deal_id: "deal-011",
    deal_title: "Chris Anderson - Real Estate Mastery Program",
    contact_name: "Chris Anderson",
    contact_phone: "+1 (555) 234-5678",
    contact_email: "chris.anderson.re@gmail.com",
    last_activity: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-050",
        role: "user",
        content: "I'm interested in the Starter Package. What's included?",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Chris Anderson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-051",
        role: "assistant",
        content: "Hi Chris! The Starter Package includes up to 5 users, core features, email support, and basic analytics. Perfect for small teams getting started. It's $99/month. Want to see a demo?",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000 + 2 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-052",
        role: "user",
        content: "That sounds reasonable. Can I try it first?",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Chris Anderson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-053",
        role: "assistant",
        content: "Absolutely! We offer a 14-day free trial with full access. No credit card required. I can set that up for you right now. Ready to get started?",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-054",
        role: "user",
        content: "Yes, let's do it!",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Chris Anderson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-055",
        role: "assistant",
        content: "Perfect! I've set up your trial account. Check your email for login credentials. I'll check in with you in a few days to see how it's going!",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "chris@gmail.com",
      },
      {
        id: "msg-056",
        role: "system",
        content: "Trial account created. Welcome email sent with login credentials.",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 11 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-057",
        role: "assistant",
        content: "Hey Chris! How's the trial going? Any questions so far?",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-058",
        role: "user",
        content: "It's going well! We're still exploring. I'll let you know if we have questions.",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Chris Anderson",
        contact_phone: "+1 (555) 234-5678",
      },
    ],
  },
  "deal-012": {
    deal_id: "deal-012",
    deal_title: "Patricia Lee - Real Estate Mastery Program",
    contact_name: "Patricia Lee",
    contact_phone: "+1 (555) 345-6789",
    contact_email: "patricia.lee.invest@gmail.com",
    last_activity: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-054",
        role: "user",
        content: "We're looking at the Professional package. What makes it different from Premium?",
        timestamp: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Patricia Lee",
        contact_email: "patricia.lee@gmail.com",
      },
      {
        id: "msg-055",
        role: "assistant",
        content: "Hi Patricia! The Professional package includes advanced features like custom workflows, API access, and priority support. Premium adds white-glove onboarding and dedicated account management. What's most important for Summit?",
        timestamp: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "patricia.lee@gmail.com",
      },
      {
        id: "msg-056",
        role: "user",
        content: "API access is important. Can you tell me more about that?",
        timestamp: new Date(Date.now() - 41 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Patricia Lee",
        contact_email: "patricia.lee@gmail.com",
      },
      {
        id: "msg-057",
        role: "assistant",
        content: "Our API is comprehensive and well-documented. It includes REST endpoints, webhooks, and SDKs for popular languages. Perfect for building custom integrations. Want to see the API docs?",
        timestamp: new Date(Date.now() - 41 * 24 * 60 * 60 * 1000 + 7 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "patricia.lee@gmail.com",
      },
      {
        id: "msg-058",
        role: "user",
        content: "Yes, please send the API docs. Also, do you have rate limits?",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Patricia Lee",
        contact_email: "patricia.lee@gmail.com",
      },
      {
        id: "msg-059",
        role: "assistant",
        content: "Great question! Professional package includes 10,000 API calls/month. Enterprise has unlimited. I'll send you the full API documentation with rate limit details.",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "patricia.lee@gmail.com",
      },
      {
        id: "msg-060",
        role: "system",
        content: "Email sent: Complete API Documentation with Rate Limits and Best Practices",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-061",
        role: "user",
        content: "Thanks! The docs look good. We'll review and get back to you.",
        timestamp: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Patricia Lee",
        contact_email: "patricia.lee@gmail.com",
      },
      {
        id: "msg-062",
        role: "assistant",
        content: "Perfect! Let me know if you have any questions. I'm here to help!",
        timestamp: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "patricia.lee@gmail.com",
      },
    ],
  },
  "deal-013": {
    deal_id: "deal-013",
    deal_title: "Emily Watson - Real Estate Mastery Program",
    contact_name: "Emily Watson",
    contact_phone: "+1 (555) 456-7890",
    contact_email: "emily.watson.invest@gmail.com",
    last_activity: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-060",
        role: "user",
        content: "We're a healthcare company. Do you have HIPAA compliance?",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Dr. Emily Watson",
        contact_email: "emily.watson@gmail.com",
      },
      {
        id: "msg-061",
        role: "assistant",
        content: "Hi Dr. Watson! Yes, we're HIPAA compliant and SOC 2 Type II certified. We have BAA agreements available and follow all healthcare data regulations. Would you like to see our compliance documentation?",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "emily.watson@gmail.com",
      },
      {
        id: "msg-062",
        role: "user",
        content: "Yes, that would be very helpful. Also, do you support HL7 integration?",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Dr. Emily Watson",
        contact_email: "emily.watson@gmail.com",
      },
      {
        id: "msg-063",
        role: "assistant",
        content: "We do support HL7 integration! I'll send you both the compliance docs and our HL7 integration guide. We've worked with many healthcare organizations.",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "emily.watson@gmail.com",
      },
      {
        id: "msg-064",
        role: "system",
        content: "Email sent: HIPAA Compliance Documentation and HL7 Integration Guide",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-065",
        role: "user",
        content: "The compliance docs look good. Can we schedule a call to discuss implementation?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Dr. Emily Watson",
        contact_email: "emily.watson@gmail.com",
      },
      {
        id: "msg-066",
        role: "assistant",
        content: "Absolutely! I'll send you a calendar invite. We can discuss your specific healthcare use case and implementation timeline.",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "emily.watson@gmail.com",
      },
      {
        id: "msg-067",
        role: "system",
        content: "Call completed - Duration: 40 minutes. Discussed HIPAA compliance, HL7 integration, and healthcare-specific requirements. Implementation plan shared.",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 456-7890",
      },
      {
        id: "msg-068",
        role: "assistant",
        content: "Hi Dr. Watson, just following up on our call. Did you have a chance to review the implementation plan?",
        timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "emily.watson@gmail.com",
      },
    ],
  },
  "deal-014": {
    deal_id: "deal-014",
    deal_title: "Michael Brown - Real Estate Mastery Program",
    contact_name: "Michael Brown",
    contact_phone: "+1 (555) 567-8901",
    contact_email: "michael.brown.re@gmail.com",
    last_activity: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-065",
        role: "user",
        content: "We're a fintech company. Security is our top priority. What security features do you offer?",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Michael Brown",
        contact_email: "michael.brown@gmail.com",
      },
      {
        id: "msg-066",
        role: "assistant",
        content: "Hi Michael! Security is our top priority too. We offer end-to-end encryption, SSO, MFA, audit logs, and we're PCI DSS Level 1 compliant. We also have SOC 2 Type II and ISO 27001 certifications. Want to see our security whitepaper?",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "michael.brown@gmail.com",
      },
      {
        id: "msg-067",
        role: "user",
        content: "Yes, please send the whitepaper. Also, do you have penetration testing reports?",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Michael Brown",
        contact_email: "michael.brown@gmail.com",
      },
      {
        id: "msg-068",
        role: "assistant",
        content: "We conduct regular penetration testing and can share our latest reports under NDA. I'll send you the security whitepaper and we can discuss the pen test reports on a call.",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "michael.brown@gmail.com",
      },
      {
        id: "msg-069",
        role: "system",
        content: "Email sent: Security Whitepaper and Compliance Certifications",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 7 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-070",
        role: "user",
        content: "The security documentation looks comprehensive. Can we schedule a security review call?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Michael Brown",
        contact_email: "michael.brown@gmail.com",
      },
      {
        id: "msg-071",
        role: "assistant",
        content: "Absolutely! I'll set up a call with our security team. They can walk you through all our security measures and answer any questions.",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "michael.brown@gmail.com",
      },
      {
        id: "msg-072",
        role: "system",
        content: "Call completed - Duration: 45 minutes. Security team reviewed all security features, compliance certifications, and answered technical questions. NDA signed for pen test reports.",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-073",
        role: "assistant",
        content: "Hi Michael, just checking in. How did the security review go with your team?",
        timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "michael.brown@gmail.com",
      },
    ],
  },
  "deal-015": {
    deal_id: "deal-015",
    deal_title: "Jessica Taylor - Real Estate Mastery Program",
    contact_name: "Jessica Taylor",
    contact_phone: "+1 (555) 678-9012",
    contact_email: "jessica.taylor.invest@gmail.com",
    last_activity: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-070",
        role: "user",
        content: "We're an online education platform. Do you support learning management system integrations?",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Jessica Taylor",
        contact_phone: "+1 (555) 678-9012",
      },
      {
        id: "msg-071",
        role: "assistant",
        content: "Hi Jessica! Yes, we integrate with popular LMS platforms like Canvas, Moodle, and Blackboard. We also support SCORM and xAPI standards. What LMS are you using?",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-072",
        role: "user",
        content: "We use Canvas. Can you show me how the integration works?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Jessica Taylor",
        contact_phone: "+1 (555) 678-9012",
      },
      {
        id: "msg-073",
        role: "assistant",
        content: "Absolutely! I can set up a demo showing the Canvas integration. It's seamless - students can access everything from their Canvas dashboard. Want to schedule a demo?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-074",
        role: "user",
        content: "Yes, that would be great! This week works for me.",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Jessica Taylor",
        contact_phone: "+1 (555) 678-9012",
      },
      {
        id: "msg-075",
        role: "assistant",
        content: "Perfect! I'll send you a calendar invite with a few time options. Looking forward to showing you the integration!",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000 + 2 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-076",
        role: "system",
        content: "Demo completed - Duration: 25 minutes. Showed Canvas integration, SCORM support, and student dashboard features. Follow-up materials sent.",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 678-9012",
      },
      {
        id: "msg-077",
        role: "user",
        content: "The demo was great! We're interested. Can you send pricing for our student count?",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jessica Taylor",
        contact_email: "jessica.taylor@gmail.com",
      },
      {
        id: "msg-078",
        role: "assistant",
        content: "Absolutely! What's your current student count? I'll prepare a custom quote based on that.",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "jessica.taylor@gmail.com",
      },
      {
        id: "msg-079",
        role: "user",
        content: "We have about 5,000 active students currently, but we're growing fast.",
        timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jessica Taylor",
        contact_email: "jessica.taylor@gmail.com",
      },
      {
        id: "msg-080",
        role: "assistant",
        content: "Perfect! I'll create a quote that scales with your growth. The Growth Package is ideal for your situation. I'll send it over today.",
        timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "jessica.taylor@gmail.com",
      },
      {
        id: "msg-081",
        role: "assistant",
        content: "Hi Jessica, just checking in on the quote. Have you had a chance to review it?",
        timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "jessica.taylor@gmail.com",
      },
    ],
  },
  "deal-016": {
    deal_id: "deal-016",
    deal_title: "Daniel Kim - Real Estate Mastery Program",
    contact_name: "Daniel Kim",
    contact_phone: "+1 (555) 789-0123",
    contact_email: "daniel.kim.re@gmail.com",
    last_activity: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-075",
        role: "user",
        content: "We're a retail chain. Do you integrate with POS systems?",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Daniel Kim",
        contact_email: "daniel.kim@gmail.com",
      },
      {
        id: "msg-076",
        role: "assistant",
        content: "Hi Daniel! Yes, we integrate with major POS systems including Square, Shopify, and custom solutions. We can sync inventory, sales data, and customer information in real-time. Which POS system are you using?",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "daniel.kim@gmail.com",
      },
      {
        id: "msg-077",
        role: "user",
        content: "We use Square. Can you show me how the integration works?",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Daniel Kim",
        contact_email: "daniel.kim@gmail.com",
      },
      {
        id: "msg-078",
        role: "assistant",
        content: "Absolutely! Square integration is one of our most popular. I can set up a demo showing real-time sync, inventory management, and customer data flow. Want to schedule that?",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "daniel.kim@gmail.com",
      },
      {
        id: "msg-079",
        role: "user",
        content: "Yes, let's do it. I'm available this week.",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Daniel Kim",
        contact_email: "daniel.kim@gmail.com",
      },
      {
        id: "msg-080",
        role: "system",
        content: "Demo completed - Duration: 30 minutes. Showed Square POS integration, inventory sync, and customer data management. Integration guide sent.",
        timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 789-0123",
      },
      {
        id: "msg-081",
        role: "user",
        content: "The demo was impressive! How long does the integration take?",
        timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Daniel Kim",
        contact_email: "daniel.kim@gmail.com",
      },
      {
        id: "msg-082",
        role: "assistant",
        content: "Square integration typically takes 1-2 days to set up. We handle the technical side, and you just need to authorize the connection. Very straightforward!",
        timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "daniel.kim@gmail.com",
      },
      {
        id: "msg-083",
        role: "assistant",
        content: "Hi Daniel, just checking in. Have you had a chance to discuss the Square integration with your team?",
        timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "daniel.kim@gmail.com",
      },
    ],
  },
  "deal-017": {
    deal_id: "deal-017",
    deal_title: "Maria Garcia - Real Estate Mastery Program",
    contact_name: "Maria Garcia",
    contact_phone: "+1 (555) 890-1234",
    contact_email: "maria.garcia.invest@gmail.com",
    last_activity: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-080",
        role: "user",
        content: "Hi! I'm interested in the Starter Package. Do you offer a free trial?",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Maria Garcia",
        contact_phone: "+1 (555) 890-1234",
      },
      {
        id: "msg-081",
        role: "assistant",
        content: "Hi Maria! Yes, we offer a 14-day free trial with full access. No credit card required. I can set that up for you right now. Ready to get started?",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 2 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-082",
        role: "user",
        content: "That sounds perfect! Let's do it.",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Maria Garcia",
        contact_phone: "+1 (555) 890-1234",
      },
      {
        id: "msg-083",
        role: "assistant",
        content: "Great! I've set up your trial account. Check your email for login credentials. I'll check in with you in a few days to see how it's going!",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 7 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "maria.garcia@gmail.com",
      },
      {
        id: "msg-084",
        role: "system",
        content: "Trial account created. Welcome email sent with login credentials and getting started guide.",
        timestamp: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-085",
        role: "assistant",
        content: "Hey Maria! How's the trial going? Any questions so far?",
        timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-086",
        role: "user",
        content: "It's going well! We're still exploring the features. I'll let you know if we have questions.",
        timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Maria Garcia",
        contact_phone: "+1 (555) 890-1234",
      },
      {
        id: "msg-087",
        role: "assistant",
        content: "Perfect! Don't hesitate to reach out if you need anything. I'm here to help!",
        timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-088",
        role: "assistant",
        content: "Hi Maria, your trial is ending soon. How's everything going? Would you like to continue with the Starter Package?",
        timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "maria.garcia@gmail.com",
      },
    ],
  },
  "deal-018": {
    deal_id: "deal-018",
    deal_title: "Kevin Nguyen - Real Estate Mastery Program",
    contact_name: "Kevin Nguyen",
    contact_phone: "+1 (555) 901-2345",
    contact_email: "kevin.nguyen.re@gmail.com",
    last_activity: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-085",
        role: "user",
        content: "We're a logistics company. Do you integrate with shipping carriers like FedEx and UPS?",
        timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Kevin Nguyen",
        contact_email: "kevin.nguyen@gmail.com",
      },
      {
        id: "msg-086",
        role: "assistant",
        content: "Hi Kevin! Yes, we have native integrations with FedEx, UPS, DHL, and USPS. You can track shipments, print labels, and manage everything from one place. Which carriers do you use most?",
        timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "kevin.nguyen@gmail.com",
      },
      {
        id: "msg-087",
        role: "user",
        content: "We use FedEx and UPS primarily. Can you show me the integration?",
        timestamp: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Kevin Nguyen",
        contact_email: "kevin.nguyen@gmail.com",
      },
      {
        id: "msg-088",
        role: "assistant",
        content: "Absolutely! I can set up a demo showing label printing, tracking, and rate comparison between carriers. Want to schedule that?",
        timestamp: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "kevin.nguyen@gmail.com",
      },
      {
        id: "msg-089",
        role: "system",
        content: "Demo completed - Duration: 35 minutes. Showed FedEx and UPS integrations, label printing, tracking, and rate comparison features. Integration guide sent.",
        timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-090",
        role: "user",
        content: "The demo was great! How quickly can we get this set up?",
        timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Kevin Nguyen",
        contact_email: "kevin.nguyen@gmail.com",
      },
      {
        id: "msg-091",
        role: "assistant",
        content: "Carrier integrations typically take 2-3 business days. We'll need your carrier account credentials and then we handle the rest. Very quick setup!",
        timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "kevin.nguyen@gmail.com",
      },
      {
        id: "msg-092",
        role: "assistant",
        content: "Hi Kevin, just checking in. Have you had a chance to discuss the carrier integrations with your team?",
        timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "kevin.nguyen@gmail.com",
      },
    ],
  },
}

export function getConversationForDeal(dealId: string): DealConversation | null {
  return demoConversations[dealId] || null
}
