// Demo conversation data for MVP
// Structured to match GoHighLevel API response format

export interface ConversationMessage {
  id: string
  role: "user" | "assistant" | "system"
  content: string
  timestamp: string
  type?: "sms" | "email" | "call" | "note"
  direction?: "inbound" | "outbound"
  contact_name?: string
  contact_phone?: string
  contact_email?: string
}

export interface DealConversation {
  deal_id: string
  deal_title: string
  contact_name: string
  contact_phone?: string
  contact_email?: string
  messages: ConversationMessage[]
  last_activity: string
}

export const demoConversations: Record<string, DealConversation> = {
  "deal-001": {
    deal_id: "deal-001",
    deal_title: "Acme Corp - Enterprise Package",
    contact_name: "Sarah Johnson",
    contact_phone: "+1 (555) 234-5678",
    contact_email: "sarah.johnson@acmecorp.com",
    last_activity: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-001",
        role: "user",
        content: "Hi! I'm interested in learning more about your Enterprise Package. Can you send me some information?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Sarah Johnson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-002",
        role: "assistant",
        content: "Absolutely! The Enterprise Package includes advanced analytics, priority support, and custom integrations. I can send you a detailed proposal. What's the best way to reach you?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-003",
        role: "user",
        content: "Email works great. I'm particularly interested in the analytics features.",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Sarah Johnson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-004",
        role: "assistant",
        content: "Perfect! I'll send over the proposal with details on our analytics suite. It includes real-time dashboards, custom reports, and predictive insights. Should I include pricing information?",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-005",
        role: "user",
        content: "Yes, please include pricing. I'll review it and get back to you.",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Sarah Johnson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-006",
        role: "assistant",
        content: "Great! I've sent the proposal to your email. Let me know if you have any questions. I'm here to help!",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "sarah.johnson@acmecorp.com",
      },
      {
        id: "msg-007",
        role: "system",
        content: "Email sent: Enterprise Package Proposal - Acme Corp",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 16 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
      {
        id: "msg-008",
        role: "system",
        content: "Call attempted - No answer. Left voicemail.",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 234-5678",
      },
    ],
  },
  "deal-002": {
    deal_id: "deal-002",
    deal_title: "TechStart Inc - Starter Package",
    contact_name: "Mike Chen",
    contact_phone: "+1 (555) 345-6789",
    contact_email: "mike.chen@techstart.io",
    last_activity: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-009",
        role: "user",
        content: "Hey, I saw your Starter Package and it looks interesting. What's included?",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Mike Chen",
        contact_phone: "+1 (555) 345-6789",
      },
      {
        id: "msg-010",
        role: "assistant",
        content: "Hi Mike! The Starter Package is perfect for growing teams. It includes up to 10 users, basic analytics, email support, and all core features. It's $99/month. Would you like to see a demo?",
        timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-011",
        role: "user",
        content: "That sounds good. Can we schedule something for next week?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Mike Chen",
        contact_phone: "+1 (555) 345-6789",
      },
      {
        id: "msg-012",
        role: "assistant",
        content: "Absolutely! I have availability Tuesday and Wednesday next week. What time works best for you?",
        timestamp: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-013",
        role: "user",
        content: "Tuesday afternoon would work. Let me check my calendar and confirm.",
        timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Mike Chen",
        contact_phone: "+1 (555) 345-6789",
      },
      {
        id: "msg-014",
        role: "system",
        content: "Call completed - Duration: 12 minutes. Discussed pricing and implementation timeline. Follow-up scheduled for next week.",
        timestamp: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 345-6789",
      },
    ],
  },
  "deal-003": {
    deal_id: "deal-003",
    deal_title: "Global Solutions - Premium",
    contact_name: "Jennifer Martinez",
    contact_phone: "+1 (555) 456-7890",
    contact_email: "j.martinez@globalsolutions.com",
    last_activity: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-015",
        role: "user",
        content: "Hi, we're looking for a solution that can scale with our international operations. Does your Premium package support multiple regions?",
        timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jennifer Martinez",
        contact_email: "j.martinez@globalsolutions.com",
      },
      {
        id: "msg-016",
        role: "assistant",
        content: "Yes! Our Premium package includes multi-region support, localized features, and 24/7 global support. We work with companies in 40+ countries. Would you like to discuss your specific requirements?",
        timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "j.martinez@globalsolutions.com",
      },
      {
        id: "msg-017",
        role: "user",
        content: "That's exactly what we need. Can you send me a custom quote?",
        timestamp: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Jennifer Martinez",
        contact_email: "j.martinez@globalsolutions.com",
      },
      {
        id: "msg-018",
        role: "assistant",
        content: "I'd be happy to! To provide the most accurate quote, could you share: 1) Number of users, 2) Primary regions, and 3) Any specific compliance requirements?",
        timestamp: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "j.martinez@globalsolutions.com",
      },
      {
        id: "msg-019",
        role: "system",
        content: "Call scheduled for tomorrow at 2 PM EST to discuss requirements",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
    ],
  },
  "deal-004": {
    deal_id: "deal-004",
    deal_title: "InnovateCo - Growth Package",
    contact_name: "David Park",
    contact_phone: "+1 (555) 567-8901",
    contact_email: "david@innovateco.com",
    last_activity: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-020",
        role: "user",
        content: "We're a fast-growing startup. What does the Growth Package offer?",
        timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "David Park",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-021",
        role: "assistant",
        content: "The Growth Package is designed for scaling companies! It includes unlimited users, advanced features, priority support, and flexible pricing that grows with you. Plus, we offer special startup discounts. Interested?",
        timestamp: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000 + 4 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-022",
        role: "user",
        content: "The startup discount sounds interesting. What's the pricing?",
        timestamp: new Date(Date.now() - 34 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "David Park",
        contact_phone: "+1 (555) 567-8901",
      },
      {
        id: "msg-023",
        role: "assistant",
        content: "For qualifying startups, we offer 20% off the first year. The Growth Package is normally $299/month, so that would be $239/month. We also have flexible payment terms. Want to see if you qualify?",
        timestamp: new Date(Date.now() - 34 * 24 * 60 * 60 * 1000 + 6 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-024",
        role: "system",
        content: "Call completed - Duration: 18 minutes. Discussed startup qualification criteria and pricing options. Sent qualification form via email.",
        timestamp: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 567-8901",
      },
    ],
  },
  "deal-005": {
    deal_id: "deal-005",
    deal_title: "ScaleUp Ventures - Enterprise",
    contact_name: "Lisa Thompson",
    contact_phone: "+1 (555) 678-9012",
    contact_email: "lisa.thompson@scaleupventures.com",
    last_activity: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-025",
        role: "user",
        content: "We're evaluating enterprise solutions. What makes yours different?",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Lisa Thompson",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
      {
        id: "msg-026",
        role: "assistant",
        content: "Our Enterprise solution offers custom integrations, dedicated account management, SLA guarantees, and white-glove onboarding. We've helped companies like yours scale from 50 to 5000+ users. Would you like to see a case study?",
        timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
      {
        id: "msg-027",
        role: "user",
        content: "Yes, that would be helpful. Also, what's the implementation timeline?",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Lisa Thompson",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
      {
        id: "msg-028",
        role: "assistant",
        content: "I'll send over the case study. For implementation, we typically see companies up and running in 2-4 weeks, depending on complexity. We provide a dedicated implementation specialist. Want to schedule a call to discuss your timeline?",
        timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "lisa.thompson@scaleupventures.com",
      },
    ],
  },
  "deal-006": {
    deal_id: "deal-006",
    deal_title: "DataFlow Systems - Pro Package",
    contact_name: "Tom Wilson",
    contact_phone: "+1 (555) 789-0123",
    contact_email: "tom.wilson@dataflow.io",
    last_activity: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-029",
        role: "user",
        content: "Hi, I'm interested in the Pro Package. What's included?",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Tom Wilson",
        contact_phone: "+1 (555) 789-0123",
      },
      {
        id: "msg-030",
        role: "assistant",
        content: "Hi Tom! The Pro Package includes up to 50 users, advanced analytics, API access, priority support, and custom integrations. It's $199/month. Perfect for mid-size teams. Want to see a demo?",
        timestamp: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000 + 3 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-031",
        role: "user",
        content: "The API access is important for us. Can you tell me more about that?",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Tom Wilson",
        contact_phone: "+1 (555) 789-0123",
      },
      {
        id: "msg-032",
        role: "assistant",
        content: "Absolutely! Our API is RESTful, well-documented, and includes webhooks. You can integrate with your existing tools, build custom workflows, and automate processes. We also provide API support and examples. Want to see the docs?",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-033",
        role: "system",
        content: "Email sent: API Documentation and Integration Guide",
        timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
    ],
  },
  "deal-007": {
    deal_id: "deal-007",
    deal_title: "CloudSync Technologies - Enterprise",
    contact_name: "Rachel Kim",
    contact_phone: "+1 (555) 890-1234",
    contact_email: "rachel.kim@cloudsync.tech",
    last_activity: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-034",
        role: "user",
        content: "Hi, we're looking for an enterprise solution that can handle our cloud infrastructure needs.",
        timestamp: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Rachel Kim",
        contact_email: "rachel.kim@cloudsync.tech",
      },
      {
        id: "msg-035",
        role: "assistant",
        content: "Hi Rachel! Our Enterprise solution is perfect for cloud infrastructure. It includes advanced security, compliance features, and seamless cloud integrations. What's your current infrastructure setup?",
        timestamp: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "rachel.kim@cloudsync.tech",
      },
      {
        id: "msg-036",
        role: "user",
        content: "We're using AWS and Azure. Do you support both?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Rachel Kim",
        contact_email: "rachel.kim@cloudsync.tech",
      },
      {
        id: "msg-037",
        role: "assistant",
        content: "Yes! We have native integrations for both AWS and Azure, plus multi-cloud support. I can send you a detailed integration guide. Would that be helpful?",
        timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "rachel.kim@cloudsync.tech",
      },
    ],
  },
  "deal-008": {
    deal_id: "deal-008",
    deal_title: "NextGen Solutions - Premium",
    contact_name: "James Rodriguez",
    contact_phone: "+1 (555) 901-2345",
    contact_email: "james.r@nextgensolutions.com",
    last_activity: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-038",
        role: "user",
        content: "We're evaluating your Premium package. What's the onboarding process like?",
        timestamp: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "James Rodriguez",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-039",
        role: "assistant",
        content: "Hi James! Our Premium package includes white-glove onboarding with a dedicated specialist. Typically takes 2-3 weeks. We handle everything from setup to training. Want to schedule a call to discuss your timeline?",
        timestamp: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-040",
        role: "user",
        content: "That sounds good. Can you send me more details about the training?",
        timestamp: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "James Rodriguez",
        contact_phone: "+1 (555) 901-2345",
      },
      {
        id: "msg-041",
        role: "system",
        content: "Call completed - Duration: 15 minutes. Discussed onboarding timeline and training options. Sent training materials via email.",
        timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        type: "call",
        direction: "outbound",
        contact_phone: "+1 (555) 901-2345",
      },
    ],
  },
  "deal-009": {
    deal_id: "deal-009",
    deal_title: "Velocity Partners - Growth Package",
    contact_name: "Amanda Foster",
    contact_phone: "+1 (555) 012-3456",
    contact_email: "amanda@velocitypartners.com",
    last_activity: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-042",
        role: "user",
        content: "We're a fast-growing company. Does the Growth Package scale with us?",
        timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Amanda Foster",
        contact_email: "amanda@velocitypartners.com",
      },
      {
        id: "msg-043",
        role: "assistant",
        content: "Absolutely! The Growth Package is designed to scale. It includes flexible user limits, usage-based pricing options, and priority support. Many companies start here and grow into Enterprise. Want to see how it scales?",
        timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "amanda@velocitypartners.com",
      },
      {
        id: "msg-044",
        role: "user",
        content: "Yes, that would be helpful. Also, what's the pricing structure?",
        timestamp: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Amanda Foster",
        contact_email: "amanda@velocitypartners.com",
      },
    ],
  },
  "deal-010": {
    deal_id: "deal-010",
    deal_title: "PrimeTech Industries - Enterprise",
    contact_name: "Robert Chen",
    contact_phone: "+1 (555) 123-4567",
    contact_email: "robert.chen@primetech.com",
    last_activity: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-045",
        role: "user",
        content: "We need an enterprise solution with custom integrations. Is that possible?",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Robert Chen",
        contact_email: "robert.chen@primetech.com",
      },
      {
        id: "msg-046",
        role: "assistant",
        content: "Hi Robert! Yes, our Enterprise package includes custom integrations. We have a dedicated integration team that works with you to build exactly what you need. What systems are you looking to integrate?",
        timestamp: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "robert.chen@primetech.com",
      },
      {
        id: "msg-047",
        role: "user",
        content: "We use Salesforce, HubSpot, and a custom ERP. Can you integrate with all of those?",
        timestamp: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Robert Chen",
        contact_email: "robert.chen@primetech.com",
      },
      {
        id: "msg-048",
        role: "assistant",
        content: "We have native integrations for Salesforce and HubSpot, and we can build custom integrations for your ERP. I'll connect you with our integration specialist. Sound good?",
        timestamp: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "robert.chen@primetech.com",
      },
      {
        id: "msg-049",
        role: "system",
        content: "Call scheduled with integration specialist for next week",
        timestamp: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
        type: "note",
        direction: "outbound",
      },
    ],
  },
  "deal-011": {
    deal_id: "deal-011",
    deal_title: "Apex Digital - Starter Package",
    contact_name: "Chris Anderson",
    contact_phone: "+1 (555) 234-5678",
    contact_email: "chris@apexdigital.com",
    last_activity: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-050",
        role: "user",
        content: "I'm interested in the Starter Package. What's included?",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Chris Anderson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-051",
        role: "assistant",
        content: "Hi Chris! The Starter Package includes up to 5 users, core features, email support, and basic analytics. Perfect for small teams getting started. It's $99/month. Want to see a demo?",
        timestamp: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000 + 2 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
      {
        id: "msg-052",
        role: "user",
        content: "That sounds reasonable. Can I try it first?",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "inbound",
        contact_name: "Chris Anderson",
        contact_phone: "+1 (555) 234-5678",
      },
      {
        id: "msg-053",
        role: "assistant",
        content: "Absolutely! We offer a 14-day free trial with full access. No credit card required. I can set that up for you right now. Ready to get started?",
        timestamp: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        type: "sms",
        direction: "outbound",
      },
    ],
  },
  "deal-012": {
    deal_id: "deal-012",
    deal_title: "Summit Enterprises - Professional",
    contact_name: "Patricia Lee",
    contact_phone: "+1 (555) 345-6789",
    contact_email: "patricia.lee@summitenterprises.com",
    last_activity: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "msg-054",
        role: "user",
        content: "We're looking at the Professional package. What makes it different from Premium?",
        timestamp: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Patricia Lee",
        contact_email: "patricia.lee@summitenterprises.com",
      },
      {
        id: "msg-055",
        role: "assistant",
        content: "Hi Patricia! The Professional package includes advanced features like custom workflows, API access, and priority support. Premium adds white-glove onboarding and dedicated account management. What's most important for Summit?",
        timestamp: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "patricia.lee@summitenterprises.com",
      },
      {
        id: "msg-056",
        role: "user",
        content: "API access is important. Can you tell me more about that?",
        timestamp: new Date(Date.now() - 41 * 24 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "inbound",
        contact_name: "Patricia Lee",
        contact_email: "patricia.lee@summitenterprises.com",
      },
      {
        id: "msg-057",
        role: "assistant",
        content: "Our API is comprehensive and well-documented. It includes REST endpoints, webhooks, and SDKs for popular languages. Perfect for building custom integrations. Want to see the API docs?",
        timestamp: new Date(Date.now() - 41 * 24 * 60 * 60 * 1000 + 7 * 60 * 60 * 1000).toISOString(),
        type: "email",
        direction: "outbound",
        contact_email: "patricia.lee@summitenterprises.com",
      },
    ],
  },
}

export function getConversationForDeal(dealId: string): DealConversation | null {
  return demoConversations[dealId] || null
}
