"""initial

Revision ID: b4c6805fbe2c
Revises: 
Create Date: 2025-12-18 00:27:23.957436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c6805fbe2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('ghl_access_token', sa.Text(), nullable=True),
    sa.Column('ghl_refresh_token', sa.Text(), nullable=True),
    sa.Column('ghl_location_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ghl_deal_id', sa.String(length=255), nullable=False),
    sa.Column('ghl_contact_id', sa.String(length=255), nullable=True),
    sa.Column('ghl_pipeline_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deal_user_activity', 'deals', ['user_id', 'last_activity_date'], unique=False)
    op.create_index(op.f('ix_deals_ghl_contact_id'), 'deals', ['ghl_contact_id'], unique=False)
    op.create_index(op.f('ix_deals_ghl_deal_id'), 'deals', ['ghl_deal_id'], unique=True)
    op.create_index(op.f('ix_deals_ghl_pipeline_id'), 'deals', ['ghl_pipeline_id'], unique=False)
    op.create_index(op.f('ix_deals_last_activity_date'), 'deals', ['last_activity_date'], unique=False)
    op.create_index(op.f('ix_deals_user_id'), 'deals', ['user_id'], unique=False)
    op.create_table('approval_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('ghl_deal_id', sa.String(length=255), nullable=False),
    sa.Column('ghl_contact_id', sa.String(length=255), nullable=True),
    sa.Column('generated_message', sa.Text(), nullable=False),
    sa.Column('edited_message', sa.Text(), nullable=True),
    sa.Column('final_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SENT', name='approvalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_queue_created_at'), 'approval_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_queue_deal_id'), 'approval_queue', ['deal_id'], unique=False)
    op.create_index(op.f('ix_approval_queue_ghl_deal_id'), 'approval_queue', ['ghl_deal_id'], unique=False)
    op.create_index(op.f('ix_approval_queue_status'), 'approval_queue', ['status'], unique=False)
    op.create_index(op.f('ix_approval_queue_user_id'), 'approval_queue', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ghl_message_id', sa.String(length=255), nullable=True),
    sa.Column('ghl_contact_id', sa.String(length=255), nullable=True),
    sa.Column('message_type', sa.Enum('SMS', 'EMAIL', 'CALL', 'NOTE', name='messagetype'), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_deal_id'), 'conversations', ['deal_id'], unique=False)
    op.create_index(op.f('ix_conversations_ghl_contact_id'), 'conversations', ['ghl_contact_id'], unique=False)
    op.create_index(op.f('ix_conversations_ghl_message_id'), 'conversations', ['ghl_message_id'], unique=True)
    op.create_index(op.f('ix_conversations_message_type'), 'conversations', ['message_type'], unique=False)
    op.create_index(op.f('ix_conversations_sent_at'), 'conversations', ['sent_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_sent_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_message_type'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_ghl_message_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_ghl_contact_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_deal_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_approval_queue_user_id'), table_name='approval_queue')
    op.drop_index(op.f('ix_approval_queue_status'), table_name='approval_queue')
    op.drop_index(op.f('ix_approval_queue_ghl_deal_id'), table_name='approval_queue')
    op.drop_index(op.f('ix_approval_queue_deal_id'), table_name='approval_queue')
    op.drop_index(op.f('ix_approval_queue_created_at'), table_name='approval_queue')
    op.drop_table('approval_queue')
    op.drop_index(op.f('ix_deals_user_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_last_activity_date'), table_name='deals')
    op.drop_index(op.f('ix_deals_ghl_pipeline_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_ghl_deal_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_ghl_contact_id'), table_name='deals')
    op.drop_index('idx_deal_user_activity', table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

